In [31]:
import numpy as np
x = np.array([[0,0,0,1],
              [0,0,1,0],
              [1,1,0,0],
              [1,1,0,1]])
wh= np.array([[0.5,0.7,0.3,0.3],
              [0.3,0.2,0.6,0.4],
              [0.2,0.1,0.1,0.3]])
wo= np.array([[0.4,0.8,0.7],
              [0.6,0.2,0.3]])
yt = np.array([[1,1,0,0],
               [0,0,1,1]])
a = np.array([[0.3,0.3,1.2,1.5],
              [0.4,0.6,0.5,0.9],
              [0.3,0.1,0.3,0.6]])
y = wo.dot(a)
yd = yt-y
d = yd.transpose().dot(wo)
dwh = 0.1 * x.dot(d).transpose()
wh = wh + dwh

dwo = 0.1 * (a.dot(yd.transpose())).transpose()

wo = wo + dwo

print(wo)
print(wh)
wo.dot(wh.dot(x.transpose()))


[[0.0286 0.6227 0.5767]
 [0.5514 0.1473 0.2733]]
[[0.4148 0.6618 0.2864 0.2012]
 [0.1556 0.1146 0.6408 0.2964]
 [0.0704 0.0264 0.1272 0.1976]]


array([[0.30427852, 0.48057344, 0.25486886, 0.55914738],
       [0.20860548, 0.28707456, 0.65989314, 0.86849862]])